version: '3.8'

services:
  app:
    build: .
    container_name: darwin-agent
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DEBUG=false
      - PORT=8000
      - HOST=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - darwin-network

networks:
  darwin-network:
    driver: bridge